[2025-01-09 15:06:57,175: INFO: main: wlcome to our custom log]
[2025-01-09 15:10:49,904: INFO: main: wlcome to our custom log]
[2025-01-10 17:22:21,063:INFO:common:yaml file: config\config.yaml loaded successfully]
[2025-01-10 17:27:08,821:INFO:common:yaml file: config\config.yaml loaded successfully]
[2025-01-10 17:27:08,842:INFO:common:yaml file: params.yaml loaded successfully]
[2025-01-10 17:27:08,850:INFO:common:created directory at: artifacts]
[2025-01-10 17:27:08,850:INFO:common:created directory at: artifacts/data_ingestion]
[2025-01-10 17:27:08,856:INFO:986331348:Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-10 17:29:12,465:INFO:986331348:Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-10 18:39:09,642:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-10 18:39:09,642:INFO:common:yaml file: config\config.yaml loaded successfully]
[2025-01-10 18:39:09,650:INFO:common:yaml file: params.yaml loaded successfully]
[2025-01-10 18:39:09,650:INFO:common:created directory at: artifacts]
[2025-01-10 18:39:09,653:INFO:common:created directory at: artifacts/data_ingestion]
[2025-01-10 18:39:11,788:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Fri, 10 Jan 2025 15:39:08 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=520=Y6eqjwqZswC0eC0_hi7CI4NeCW6XJWcvWXLGpnizO5dAuyzud9IZINjvQV6ElKLzsUjPYvXGn8pRIs4HtsVEslvbIQveNj2pi7M_F_TaFtyWUOUrBbVJxK_pSgP3R8RLaomAhHyM4Oi06x_5W0GS38E42ZMJXy1B-bxAjcJGuJ9bT71a94GSIA; expires=Sat, 12-Jul-2025 15:39:08 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2025-01-10 18:39:12,171:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "C:\Users\WEB\anaconda3\envs\kidney\lib\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\WEB\anaconda3\envs\kidney\lib\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\WEB\anaconda3\envs\kidney\lib\zipfile.py", line 1271, in __init__
    self._RealGetContents()
  File "C:\Users\WEB\anaconda3\envs\kidney\lib\zipfile.py", line 1338, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-01-10 19:22:58,204:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-10 19:22:58,204:INFO:common:yaml file: config\config.yaml loaded successfully]
[2025-01-10 19:22:58,204:INFO:common:yaml file: params.yaml loaded successfully]
[2025-01-10 19:22:58,204:INFO:common:created directory at: artifacts]
[2025-01-10 19:22:58,204:INFO:common:created directory at: artifacts/data_ingestion]
[2025-01-10 19:22:58,204:INFO:data_ingestion:File already exists of size: ~ 31 KB]
[2025-01-10 19:22:58,204:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "C:\Users\WEB\anaconda3\envs\kidney\lib\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\WEB\anaconda3\envs\kidney\lib\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\WEB\anaconda3\envs\kidney\lib\zipfile.py", line 1271, in __init__
    self._RealGetContents()
  File "C:\Users\WEB\anaconda3\envs\kidney\lib\zipfile.py", line 1338, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-02-05 13:58:23,083:INFO:common:yaml file: config\config.yaml loaded successfully]
[2025-02-05 13:58:23,452:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-05 13:58:23,518:INFO:common:created directory at: artifacts]
[2025-02-05 13:58:23,519:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-05 13:58:23,519:INFO:986331348:Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-05 13:59:32,950:INFO:986331348:Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
